# Generated by Django 2.0.5 on 2018-06-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180607_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebookURL',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='githubUserName',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagramURL',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedinURL',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitterURL',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='youtubeURL',
            new_name='youtube',
        ),
    ]
