# Generated by Django 2.0.5 on 2018-07-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_experience_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
