# Generated by Django 2.0.5 on 2018-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180711_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
    ]
