# Generated by Django 2.0.5 on 2018-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180712_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/backgrounds'),
        ),
    ]
