# Generated by Django 2.0.5 on 2018-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180713_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('<=5', '<=5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('20+', '20+')], max_length=255, null=True),
        ),
    ]
