# Generated by Django 2.0.5 on 2018-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_testimonal'),
        ('accounts', '0017_remove_profile_skills'),
    ]

    operations = [
    ]
