# Generated by Django 2.0.5 on 2018-08-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_education_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
    ]
