# Generated by Django 2.0.5 on 2018-09-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180904_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='https://i.imgur.com/AAfxTCq.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
