# Generated by Django 2.0.5 on 2018-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0004_auto_20180907_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
