# Generated by Django 2.0.5 on 2018-06-07 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='uploads/avatars')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('backgroundImage', models.ImageField(upload_to='uploads/backgrounds')),
                ('bio', models.TextField()),
                ('twitterURL', models.CharField(max_length=100)),
                ('facebookURL', models.CharField(max_length=100)),
                ('linkedinURL', models.CharField(max_length=100)),
                ('instagramURL', models.CharField(max_length=100)),
                ('youtubeURL', models.CharField(max_length=100)),
                ('githubUserName', models.CharField(max_length=50)),
                ('donator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Information',
            },
        ),
    ]
