# Generated by Django 2.0.5 on 2018-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/backgrounds'),
        ),
    ]
