# Generated by Django 2.0.5 on 2018-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
