# Generated by Django 2.0.5 on 2018-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180711_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/backgrounds'),
        ),
    ]
