# Generated by Django 2.0.5 on 2018-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180713_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testimonal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
