# Generated by Django 2.0.5 on 2018-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0006_auto_20180716_2153'),
        ('accounts', '0015_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='Skills.Skill'),
        ),
    ]
