# Generated by Django 2.0.5 on 2018-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180906_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.CharField(default='https://i.imgur.com/rlaUnMY.jpg', max_length=255),
        ),
    ]
