# Generated by Django 2.0.5 on 2018-09-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180906_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.imgur.com/AAfxTCq.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundImage',
            field=models.CharField(blank=True, default='https://i.imgur.com/rlaUnMY.jpg', max_length=255),
        ),
    ]
