# Generated by Django 2.0.5 on 2018-06-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='DisplayName',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='Name',
            new_name='name',
        ),
    ]
