# Generated by Django 2.0.5 on 2018-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skillID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
