# Generated by Django 2.0.5 on 2018-06-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_auto_20180606_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='displayName',
            new_name='DisplayName',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='name',
            new_name='Name',
        ),
    ]
