# Generated by Django 2.0.5 on 2018-07-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0004_auto_20180716_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillslist',
            name='profileID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='accounts.Profile'),
        ),
    ]
