# Generated by Django 2.0.5 on 2018-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0005_auto_20180716_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='skillslist',
            name='profileID',
        ),
        migrations.DeleteModel(
            name='SkillsList',
        ),
    ]
