# Generated by Django 2.0.5 on 2018-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0008_auto_20180717_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
