# Generated by Django 2.0.5 on 2018-09-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0003_auto_20180904_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='chargeID',
        ),
        migrations.AddField(
            model_name='donation',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
