# Generated by Django 2.0.5 on 2018-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllist',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
