# Generated by Django 2.0.5 on 2018-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_auto_20180710_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Skill List',
            },
        ),
        migrations.DeleteModel(
            name='SkillList',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name',
        ),
        migrations.AddField(
            model_name='skills',
            name='skillsID',
            field=models.ManyToManyField(to='Skills.SkillsList'),
        ),
    ]
