# Generated by Django 2.0.5 on 2018-09-10 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_auto_20180910_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='skill_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
