# Generated by Django 2.0.5 on 2018-07-17 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0007_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
